apiVersion: v1
kind: Service
metadata:
  labels:
    app: kelio
  name: kleio
  namespace: dok
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: kleio-web